2024-09-15 21:46:37,124 INFO    StreamThr :27812 [internal.py:wandb_internal():85] W&B internal server running at pid: 27812, started at: 2024-09-15 21:46:37.123051
2024-09-15 21:46:37,126 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: status
2024-09-15 21:46:37,128 INFO    WriterThread:27812 [datastore.py:open_for_write():87] open: E:\DeepPurposePlusPlus\wandb\run-20240915_214637-36fcn6j6\run-36fcn6j6.wandb
2024-09-15 21:46:37,131 DEBUG   SenderThread:27812 [sender.py:send():379] send: header
2024-09-15 21:46:37,294 DEBUG   SenderThread:27812 [sender.py:send():379] send: run
2024-09-15 21:46:37,980 INFO    SenderThread:27812 [dir_watcher.py:__init__():211] watching files in: E:\DeepPurposePlusPlus\wandb\run-20240915_214637-36fcn6j6\files
2024-09-15 21:46:37,980 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: check_version
2024-09-15 21:46:37,980 INFO    SenderThread:27812 [sender.py:_start_run_threads():1188] run started: 36fcn6j6 with start time 1726429597.125387
2024-09-15 21:46:37,981 DEBUG   SenderThread:27812 [sender.py:send_request():406] send_request: check_version
2024-09-15 21:46:38,245 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: run_start
2024-09-15 21:46:38,751 DEBUG   HandlerThread:27812 [system_info.py:__init__():26] System info init
2024-09-15 21:46:38,752 DEBUG   HandlerThread:27812 [system_info.py:__init__():41] System info init done
2024-09-15 21:46:38,752 INFO    HandlerThread:27812 [system_monitor.py:start():194] Starting system monitor
2024-09-15 21:46:38,753 INFO    SystemMonitor:27812 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-15 21:46:38,753 INFO    HandlerThread:27812 [system_monitor.py:probe():214] Collecting system info
2024-09-15 21:46:38,762 INFO    SystemMonitor:27812 [interfaces.py:start():188] Started cpu monitoring
2024-09-15 21:46:38,764 INFO    SystemMonitor:27812 [interfaces.py:start():188] Started disk monitoring
2024-09-15 21:46:38,765 INFO    SystemMonitor:27812 [interfaces.py:start():188] Started gpu monitoring
2024-09-15 21:46:38,770 DEBUG   HandlerThread:27812 [system_info.py:probe():152] Probing system
2024-09-15 21:46:38,777 INFO    SystemMonitor:27812 [interfaces.py:start():188] Started memory monitoring
2024-09-15 21:46:38,788 DEBUG   HandlerThread:27812 [system_info.py:_probe_git():137] Probing git
2024-09-15 21:46:38,788 INFO    SystemMonitor:27812 [interfaces.py:start():188] Started network monitoring
2024-09-15 21:46:38,879 DEBUG   HandlerThread:27812 [system_info.py:_probe_git():145] Probing git done
2024-09-15 21:46:38,879 DEBUG   HandlerThread:27812 [system_info.py:probe():200] Probing system done
2024-09-15 21:46:38,879 DEBUG   HandlerThread:27812 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.18', 'heartbeatAt': '2024-09-15T19:46:38.770597', 'startedAt': '2024-09-15T19:46:37.105759', 'docker': None, 'cuda': None, 'args': ('--target_encoding', 'DGL_GCN', '--seed', '7', '--lr', '0.00001', '--wandb_proj', 'DeepPurposePP', '--epochs', '60'), 'state': 'running', 'program': 'E:\\DeepPurposePlusPlus\\train\\subcellular.py', 'codePathLocal': 'train\\subcellular.py', 'codePath': 'train\\subcellular.py', 'git': {'remote': 'https://github.com/jiaqingxie/ProB.git', 'commit': 'c395098df42c737d4df2cf289cb7095e18dd08b9'}, 'email': 'jiaxie@student.ethz.ch', 'root': 'E:/DeepPurposePlusPlus', 'host': 'DESKTOP-E5HJ25M', 'username': '嘉庆', 'executable': 'E:\\anaconda3\\envs\\graph\\python.exe', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 2100.0, 'min': 0.0, 'max': 2100.0}, 'cpu_freq_per_core': [{'current': 2100.0, 'min': 0.0, 'max': 2100.0}], 'disk': {'/': {'total': 214.84276962280273, 'used': 73.30566787719727}}, 'gpu': 'NVIDIA GeForce RTX 4070 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4070 Laptop GPU', 'memory_total': 8585740288}], 'memory': {'total': 15.745964050292969}}
2024-09-15 21:46:38,879 INFO    HandlerThread:27812 [system_monitor.py:probe():224] Finished collecting system info
2024-09-15 21:46:38,879 INFO    HandlerThread:27812 [system_monitor.py:probe():227] Publishing system info
2024-09-15 21:46:38,879 DEBUG   HandlerThread:27812 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-09-15 21:46:38,880 ERROR   HandlerThread:27812 [system_info.py:_save_conda():223] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 216, in _save_conda
    subprocess.call(
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-09-15 21:46:38,880 DEBUG   HandlerThread:27812 [system_info.py:_save_conda():224] Saving conda packages done
2024-09-15 21:46:38,882 INFO    HandlerThread:27812 [system_monitor.py:probe():229] Finished publishing system info
2024-09-15 21:46:38,887 DEBUG   SenderThread:27812 [sender.py:send():379] send: files
2024-09-15 21:46:38,887 INFO    SenderThread:27812 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-09-15 21:46:38,983 INFO    Thread-16 :27812 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240915_214637-36fcn6j6\files\wandb-metadata.json
2024-09-15 21:46:38,983 INFO    Thread-16 :27812 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240915_214637-36fcn6j6\files\conda-environment.yaml
2024-09-15 21:46:39,022 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: python_packages
2024-09-15 21:46:39,022 DEBUG   SenderThread:27812 [sender.py:send_request():406] send_request: python_packages
2024-09-15 21:46:39,023 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: stop_status
2024-09-15 21:46:39,023 DEBUG   SenderThread:27812 [sender.py:send_request():406] send_request: stop_status
2024-09-15 21:46:39,024 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-15 21:46:39,471 DEBUG   SenderThread:27812 [sender.py:send():379] send: telemetry
2024-09-15 21:46:39,471 DEBUG   SenderThread:27812 [sender.py:send():379] send: config
2024-09-15 21:46:39,578 INFO    wandb-upload_0:27812 [upload_job.py:push():130] Uploaded file C:\Users\嘉庆\AppData\Local\Temp\tmpl5nmhze0wandb\x3n00m6u-wandb-metadata.json
2024-09-15 21:46:39,993 INFO    Thread-16 :27812 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240915_214637-36fcn6j6\files\requirements.txt
2024-09-15 21:46:39,993 INFO    Thread-16 :27812 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240915_214637-36fcn6j6\files\output.log
2024-09-15 21:46:40,912 ERROR   gpu       :27812 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-15 21:46:40,912 ERROR   gpu       :27812 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-15 21:46:42,006 INFO    Thread-16 :27812 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240915_214637-36fcn6j6\files\output.log
2024-09-15 21:46:42,499 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: status_report
2024-09-15 21:46:43,324 ERROR   gpu       :27812 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-15 21:46:43,324 ERROR   gpu       :27812 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-15 21:46:45,715 ERROR   gpu       :27812 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-15 21:46:45,715 ERROR   gpu       :27812 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-15 21:46:47,557 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: status_report
2024-09-15 21:46:50,200 ERROR   gpu       :27812 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-15 21:46:50,200 ERROR   gpu       :27812 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-15 21:46:52,607 DEBUG   HandlerThread:27812 [handler.py:handle_request():158] handle_request: status_report
2024-09-15 21:46:52,857 INFO    cpu       :27812 [interfaces.py:monitor():138] Process cpu has exited.
2024-09-15 21:46:52,858 DEBUG   SystemMonitor:27812 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-15 21:46:52,858 DEBUG   SystemMonitor:27812 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-15 21:46:52,858 DEBUG   SystemMonitor:27812 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-15 21:46:52,859 DEBUG   SenderThread:27812 [sender.py:send():379] send: stats
2024-09-15 21:46:54,297 WARNING StreamThr :27812 [internal.py:is_dead():413] Internal process exiting, parent pid 7736 disappeared
2024-09-15 21:46:54,297 ERROR   StreamThr :27812 [internal.py:wandb_internal():151] Internal process shutdown.
2024-09-15 21:46:54,399 INFO    MainThread:27812 [internal.py:handle_exit():75] Internal process exited
