2024-09-23 10:18:28,709 INFO    StreamThr :19488 [internal.py:wandb_internal():85] W&B internal server running at pid: 19488, started at: 2024-09-23 10:18:28.708711
2024-09-23 10:18:28,711 DEBUG   HandlerThread:19488 [handler.py:handle_request():158] handle_request: status
2024-09-23 10:18:28,718 INFO    WriterThread:19488 [datastore.py:open_for_write():87] open: E:\DeepPurposePlusPlus\wandb\run-20240923_101828-kkzqfyla\run-kkzqfyla.wandb
2024-09-23 10:18:28,719 DEBUG   SenderThread:19488 [sender.py:send():379] send: header
2024-09-23 10:18:28,764 DEBUG   SenderThread:19488 [sender.py:send():379] send: run
2024-09-23 10:18:29,202 INFO    SenderThread:19488 [dir_watcher.py:__init__():211] watching files in: E:\DeepPurposePlusPlus\wandb\run-20240923_101828-kkzqfyla\files
2024-09-23 10:18:29,202 INFO    SenderThread:19488 [sender.py:_start_run_threads():1188] run started: kkzqfyla with start time 1727079508.711925
2024-09-23 10:18:29,207 DEBUG   HandlerThread:19488 [handler.py:handle_request():158] handle_request: check_version
2024-09-23 10:18:29,207 DEBUG   SenderThread:19488 [sender.py:send_request():406] send_request: check_version
2024-09-23 10:18:29,286 DEBUG   HandlerThread:19488 [handler.py:handle_request():158] handle_request: run_start
2024-09-23 10:18:29,803 DEBUG   HandlerThread:19488 [system_info.py:__init__():26] System info init
2024-09-23 10:18:29,804 DEBUG   HandlerThread:19488 [system_info.py:__init__():41] System info init done
2024-09-23 10:18:29,805 INFO    HandlerThread:19488 [system_monitor.py:start():194] Starting system monitor
2024-09-23 10:18:29,805 INFO    SystemMonitor:19488 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-23 10:18:29,805 INFO    HandlerThread:19488 [system_monitor.py:probe():214] Collecting system info
2024-09-23 10:18:29,810 INFO    SystemMonitor:19488 [interfaces.py:start():188] Started cpu monitoring
2024-09-23 10:18:29,810 INFO    SystemMonitor:19488 [interfaces.py:start():188] Started disk monitoring
2024-09-23 10:18:29,811 INFO    SystemMonitor:19488 [interfaces.py:start():188] Started gpu monitoring
2024-09-23 10:18:29,818 INFO    SystemMonitor:19488 [interfaces.py:start():188] Started memory monitoring
2024-09-23 10:18:29,830 INFO    SystemMonitor:19488 [interfaces.py:start():188] Started network monitoring
2024-09-23 10:18:29,835 DEBUG   HandlerThread:19488 [system_info.py:probe():152] Probing system
2024-09-23 10:18:29,835 DEBUG   HandlerThread:19488 [system_info.py:_probe_git():137] Probing git
2024-09-23 10:18:29,913 DEBUG   HandlerThread:19488 [system_info.py:_probe_git():145] Probing git done
2024-09-23 10:18:29,913 DEBUG   HandlerThread:19488 [system_info.py:probe():200] Probing system done
2024-09-23 10:18:29,913 DEBUG   HandlerThread:19488 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.18', 'heartbeatAt': '2024-09-23T08:18:29.835884', 'startedAt': '2024-09-23T08:18:28.701255', 'docker': None, 'cuda': None, 'args': ('--target_encoding', 'DGL_NeuralFP', '--seed', '100', '--wandb_proj', 'DeepPurposePP', '--lr', '0.00001', '--epochs', '100'), 'state': 'running', 'program': 'E:\\DeepPurposePlusPlus\\train\\yeast_ppi.py', 'codePathLocal': 'train\\yeast_ppi.py', 'codePath': 'train\\yeast_ppi.py', 'git': {'remote': 'https://github.com/jiaqingxie/ProB.git', 'commit': 'ef84d631fe7187f2baec682cfb00061253bd3006'}, 'email': 'jiaxie@student.ethz.ch', 'root': 'E:/DeepPurposePlusPlus', 'host': 'DESKTOP-E5HJ25M', 'username': '嘉庆', 'executable': 'E:\\anaconda3\\envs\\graph\\python.exe', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 1453.0, 'min': 0.0, 'max': 2100.0}, 'cpu_freq_per_core': [{'current': 1453.0, 'min': 0.0, 'max': 2100.0}], 'disk': {'/': {'total': 214.84276962280273, 'used': 75.60843276977539}}, 'gpu': 'NVIDIA GeForce RTX 4070 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4070 Laptop GPU', 'memory_total': 8585740288}], 'memory': {'total': 15.745964050292969}}
2024-09-23 10:18:29,913 INFO    HandlerThread:19488 [system_monitor.py:probe():224] Finished collecting system info
2024-09-23 10:18:29,914 INFO    HandlerThread:19488 [system_monitor.py:probe():227] Publishing system info
2024-09-23 10:18:29,914 DEBUG   HandlerThread:19488 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-09-23 10:18:29,915 ERROR   HandlerThread:19488 [system_info.py:_save_conda():223] Error saving conda packages: [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "E:\anaconda3\envs\graph\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 216, in _save_conda
    subprocess.call(
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\anaconda3\envs\graph\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2024-09-23 10:18:29,960 DEBUG   HandlerThread:19488 [system_info.py:_save_conda():224] Saving conda packages done
2024-09-23 10:18:29,960 INFO    HandlerThread:19488 [system_monitor.py:probe():229] Finished publishing system info
2024-09-23 10:18:29,974 DEBUG   SenderThread:19488 [sender.py:send():379] send: files
2024-09-23 10:18:29,974 INFO    SenderThread:19488 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-09-23 10:18:30,211 INFO    Thread-16 :19488 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240923_101828-kkzqfyla\files\wandb-metadata.json
2024-09-23 10:18:30,211 INFO    Thread-16 :19488 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240923_101828-kkzqfyla\files\conda-environment.yaml
2024-09-23 10:18:30,491 DEBUG   HandlerThread:19488 [handler.py:handle_request():158] handle_request: python_packages
2024-09-23 10:18:30,491 DEBUG   SenderThread:19488 [sender.py:send_request():406] send_request: python_packages
2024-09-23 10:18:30,491 DEBUG   HandlerThread:19488 [handler.py:handle_request():158] handle_request: stop_status
2024-09-23 10:18:30,492 DEBUG   SenderThread:19488 [sender.py:send_request():406] send_request: stop_status
2024-09-23 10:18:30,493 DEBUG   HandlerThread:19488 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-23 10:18:30,504 INFO    wandb-upload_0:19488 [upload_job.py:push():130] Uploaded file C:\Users\嘉庆\AppData\Local\Temp\tmph5raq4kpwandb\6zj5nxz1-wandb-metadata.json
2024-09-23 10:18:30,674 DEBUG   SenderThread:19488 [sender.py:send():379] send: telemetry
2024-09-23 10:18:30,674 DEBUG   SenderThread:19488 [sender.py:send():379] send: config
2024-09-23 10:18:31,211 INFO    Thread-16 :19488 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240923_101828-kkzqfyla\files\requirements.txt
2024-09-23 10:18:31,211 INFO    Thread-16 :19488 [dir_watcher.py:_on_file_created():271] file/dir created: E:\DeepPurposePlusPlus\wandb\run-20240923_101828-kkzqfyla\files\output.log
2024-09-23 10:18:33,223 INFO    Thread-16 :19488 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\DeepPurposePlusPlus\wandb\run-20240923_101828-kkzqfyla\files\output.log
2024-09-23 10:18:33,891 ERROR   gpu       :19488 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-23 10:18:33,891 ERROR   gpu       :19488 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-23 10:18:34,050 DEBUG   HandlerThread:19488 [handler.py:handle_request():158] handle_request: status_report
2024-09-23 10:18:36,284 ERROR   gpu       :19488 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-23 10:18:36,284 ERROR   gpu       :19488 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-23 10:18:38,670 ERROR   gpu       :19488 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-23 10:18:38,670 ERROR   gpu       :19488 [interfaces.py:monitor():142] Failed to sample metric: Unknown Error
2024-09-23 10:18:39,095 DEBUG   HandlerThread:19488 [handler.py:handle_request():158] handle_request: status_report
2024-09-23 10:18:41,880 INFO    cpu       :19488 [interfaces.py:monitor():138] Process cpu has exited.
2024-09-23 10:18:41,882 DEBUG   SystemMonitor:19488 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-23 10:18:41,882 DEBUG   SystemMonitor:19488 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-23 10:18:41,882 DEBUG   SystemMonitor:19488 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-23 10:18:41,885 DEBUG   SenderThread:19488 [sender.py:send():379] send: stats
2024-09-23 10:18:43,412 INFO    MainThread:19488 [internal.py:handle_exit():75] Internal process exited
